  <!-- Hide from old browsers
  iArray=new Array(
"images/front1/01 nias.jpg",
"images/front1/10 tanimbar.jpg",
"images/front1/afo.jpg",
"images/front1/bactiar5.JPG",
"images/front1/bell102.JPG",
"images/front1/bracelet2.JPG",
"images/front1/coins2.JPG",
"images/front1/dongsonaxe01.jpg",
"images/front1/gold12.JPG",
"images/front1/gold13.JPG",
"images/front1/h.JPG",
"images/front1/holy2.jpg",
"images/front1/java.jpg",
"images/front1/java01107.jpg",
"images/front1/java01110.jpg",
"images/front1/java01113.jpg",
"images/front1/lambab.jpg",
"images/front1/lambaspec1.jpg",
"images/front1/maluku3headsdet.jpg",
"images/front1/maranga1.jpg",
"images/front1/maranga2.jpg",
"images/front1/mask01.jpg",
"images/front1/P1010002_2.JPG",
"images/front1/P1010010.JPG",
"images/front1/P1010022.JPG",
"images/front1/padang.jpg",
"images/front1/padung.JPG",
"images/front1/Pic00007_2.jpg",
"images/front1/PIC00008_2.JPG",
"images/front1/plate02.jpg",
"images/front1/pot02.jpg",
"images/front1/precoback.jpg",
"images/front1/shiva com.jpg",
"images/front1/stamp2a.jpg",
"images/front1/tanimbarchair.jpg",
"images/front1/taraba.jpg",
"images/front1/teke.JPG",
"images/front1/torque.jpg",
"images/front1/Vase01.jpg",
"images/front1/vishnua.jpg"
);
  ni=Math.floor(iArray.length*Math.random());
  ni='<IMG SRC="'+ iArray[ni]+ '" BORDER=0>';
// end hiding -->